#pragma once
#include <stdint.h>
#include <stddef.h>

/* Generated by Cedar codegen */
typedef struct {
    uint8_t _b[10];
} Student;

uint32_t Student_get_id(const Student* s);
void Student_set_id(Student* s, uint32_t v);

uint16_t Student_get_age(const Student* s);
void Student_set_age(Student* s, uint16_t v);

float Student_get_gpa(const Student* s);
void Student_set_gpa(Student* s, float v);

