-- string backend 

{-# LANGUAGE OverloadedStrings #-}
module Cedar.CodeGen.CodeGen
  ( emitHeader
  , emitImpl
  ) where

import qualified Data.Map as M
import Data.Char (toLower, toUpper)
import Data.Bits (shiftL)
import Data.List (intercalate, scanl')
import Cedar.CodeGen.Allocation (AlignedBitRange(..))
import Cedar.Layout.Surface (Endianness(..))
import Cedar.Layout.Core

-- ===== public files =====

emitHeader :: String -> Int -> String
emitHeader typeName wordCount =
  unlines
    [ "// This file is generated by Cedar"
    , ""
    , "#ifndef " ++ guard typeName ++ "__"
    , "#define " ++ guard typeName ++ "__"
    , ""
    , "#include <stdint.h>"
    , ""
    , "struct " ++ typeName ++ " {"
    , "  unsigned int data[" ++ show wordCount ++ "U];"
    , "};"
    , "typedef struct " ++ typeName ++ " " ++ typeName ++ ";"
    , ""
    , "#endif"
    ]
  where guard nm = map (\c -> if c == ' ' then '_' else toUpper c) nm

emitImpl :: String -> [(String, [AlignedBitRange], Endianness)] -> String
emitImpl typeName parts =
  unlines $
    [ "// This file is generated by Cedar"
    , ""
    , "#include <stdint.h>"
    , "#include \"" ++ map toLower typeName ++ ".h\""
    , ""
    ]
    ++ map (\(_fld, brs, e) -> emitFieldFns typeName brs e) parts
  where
    uncurry3 f (a,b,c) = f a b c

-- ===== per-field code =====

emitFieldFns
  :: String                   -- struct name (e.g., t1)
  -> [AlignedBitRange]        -- split into 32-bit lanes
  -> Endianness               -- ME/LE/BE on the embedded value
  -> String                   -- concatenated C code (get_part*, get, set_part*, set)
emitFieldFns typeName brs ω =
  let partNames = [ fresh ("d_part" ++ show i) | i <- [0..length brs - 1] ]
      -- getters for each part
      partGets  = zipWith (mkPartGet typeName) partNames brs
      -- final get that assembles them
      getFun    = mkWholeGet partNames
      -- setters for each part
      partSets  = zipWith (mkPartSet typeName) partNames brs
      -- final set that slices value
      setFun    = mkWholeSet partNames brs
  in unlines (partGets ++ [getFun] ++ partSets ++ [setFun])
  where
    fresh base = base  -- prefix with field name when wiring this to field names

    mkPartGet tn nm (AlignedBitRange sz boff woff) =
      unlines
        [ "static inline unsigned int " ++ nm ++ "(" ++ tn ++ " *b)"
        , "{"
        , "  return (b->data[" ++ show woff ++ "U] >> " ++ show boff ++ "U) & " ++ show (mask sz) ++ "U;"
        , "}"
        ]
    mkWholeGet partNs =
      let shifts = scanl' (+) 0 [ bitSizeABR r | r <- brs ]
          terms  = zipWith (\n s -> "( (uint64_t)" ++ n ++ "(b) << " ++ show s ++ "U )") partNs shifts
      in  unlines
        [ "static inline uint64_t get_field(" ++ typeName ++ " *b)"
        , "{"
        , "  return " ++ intercalate " | " terms ++ ";"
        , "}"
        ]
    mkPartSet tn nm (AlignedBitRange sz boff woff) =
      unlines
        [ "static inline void " ++ nm ++ "_set(" ++ tn ++ " *b, unsigned int v)"
        , "{"
        , "  b->data[" ++ show woff ++ "U] ="
        , "      (b->data[" ++ show woff ++ "U] & ~(" ++ show (mask sz) ++ "U << " ++ show boff ++ "U))"
        , "    | (((" ++ show (mask sz) ++ "U & v) << " ++ show boff ++ "U));"
        , "}"
        ]
    mkWholeSet partNs ranges =
      let offsets = scanl' (+) 0 [ bitSizeABR r | r <- ranges ]
          lines'  = zipWith
                      (\n off -> "  " ++ n ++ "_set(b, (unsigned int)((v >> " ++ show off ++ "U) & " ++ show (mask (sizeAtOff off)) ++ "U));")
                      partNs offsets
          sizeAtOff off =
            let idx = length (takeWhile (< off) offsets)
            in bitSizeABR (ranges !! idx)
      in unlines
        [ "static inline void set_field(" ++ typeName ++ " *b, uint64_t v)"
        , "{"
        ] ++ unlines lines' ++ "}\n"

    mask :: Integer -> Integer
    mask nBits
      | nBits <= 0 = 0
      | nBits >= 32 = 0xFFFFFFFF
      | otherwise = (1 `shiftL` fromIntegral nBits) - 1
