{-# LANGUAGE OverloadedStrings #-}
module Cedar.CodeGen.CodeGen
  ( emitHeader
  , emitImpl
  ) where

import Data.Char (toUpper)
import Data.List (intercalate, scanl')
import Data.Bits (shiftL)
import Cedar.CodeGen.Allocation (AlignedBitRange(..))
import Cedar.Layout.ToCodeGen (CGStruct(..), CGField(..))
import Cedar.Layout.Surface (Endianness(..))
import Cedar.Compat.Basic (Size(..))

-- ===== public files =====

emitHeader :: CGStruct -> String
emitHeader (CGStruct typeName wordCount fields) =
  unlines
    [ "// This file is generated by Cedar"
    , ""
    , "#ifndef " ++ guard typeName ++ "__"
    , "#define " ++ guard typeName ++ "__"
    , ""
    , "#include <stdint.h>"
    , ""
    , "struct " ++ typeName ++ " {"
    , "  unsigned int data[" ++ show wordCount ++ "U];"
    , "};"
    , "typedef struct " ++ typeName ++ " " ++ typeName ++ ";"
    , ""
    ]
    ++ unlines (concatMap protoForField fields)
    ++ "#endif\n"
  where
    guard nm = map (\c -> if c == ' ' then '_' else toUpper c) nm
    cRetType f = if totalBits (cgRanges f) <= 32 then "unsigned int" else "uint64_t"
    protoForField f =
      [ cRetType f ++ " d_get_" ++ cgName f ++ "(const " ++ typeName ++ " *b);"
      , "void d_set_" ++ cgName f ++ "(" ++ typeName ++ " *b, " ++ cRetType f ++ " v);"
      , ""
      ]

emitImpl :: CGStruct -> String
emitImpl (CGStruct typeName _ fields) =
  unlines $
    [ "// This file is generated by Cedar"
    , ""
    , "#include <stdint.h>"
    , "#include \"" ++ map toLower' typeName ++ ".h\""
    , ""
    ]
    ++ concatMap (emitFieldFns typeName) fields
  where
    toLower' c | 'A' <= c && c <= 'Z' = toEnum (fromEnum c + 32)
               | otherwise            = c

-- ===== per-field code =====

emitFieldFns :: String -> CGField -> [String]
emitFieldFns typeName (CGField fname brs ω) =
  let partGetNames = [ "d_get_" ++ fname ++ "_part" ++ show i | i <- [0..length brs - 1] ]
      partSetNames = [ "d_set_" ++ fname ++ "_part" ++ show i | i <- [0..length brs - 1] ]
      -- getters for each part (static, file-local)
      partGets  = zipWith (mkPartGet typeName) partGetNames brs
      -- final get that assembles them (endianness-aware)
      getFun    = mkWholeGet typeName ω fname partGetNames brs
      -- setters for each part (static, file-local)
      partSets  = zipWith (mkPartSet typeName) partSetNames brs
      -- final set that slices value (endianness-aware)
      setFun    = mkWholeSet typeName ω fname partSetNames brs
  in partGets ++ [getFun] ++ partSets ++ [setFun]

  where
    mkPartGet :: String -> String -> AlignedBitRange -> String
    mkPartGet tn nm (AlignedBitRange sz boff woff) =
      unlines
        [ "static unsigned int " ++ nm ++ "(const " ++ tn ++ " *b)"
        , "{"
        , "  return (b->data[" ++ show woff ++ "U] >> " ++ show boff ++ "U) & " ++ show (mask32 sz) ++ "U;"
        , "}"
        ]

    mkWholeGet :: String -> Endianness -> String -> [String] -> [AlignedBitRange] -> String
    mkWholeGet tn omega nm partNs ranges =
      let sizes  = map (fromIntegral . bitSizeABR) ranges :: [Int]
          shifts = shiftsFor omega sizes
          total  = sum sizes
          retTy  = if total <= 32 then "unsigned int" else "uint64_t"
          terms  = zipWith
                     (\fn off -> "( (uint64_t)" ++ fn ++ "(b) << " ++ show off ++ "U )")
                     partNs
                     shifts
      in  unlines
            [ retTy ++ " d_get_" ++ nm ++ "(const " ++ tn ++ " *b)"
            , "{"
            , "  return " ++ intercalate " | " terms ++ ";"
            , "}"
            ]

    mkPartSet :: String -> String -> AlignedBitRange -> String
    mkPartSet tn nm (AlignedBitRange sz boff woff) =
      unlines
        [ "static void " ++ nm ++ "(" ++ tn ++ " *b, unsigned int v)"
        , "{"
        , "  b->data[" ++ show woff ++ "U] ="
        , "      (b->data[" ++ show woff ++ "U] & ~(" ++ show (mask32 sz) ++ "U << " ++ show boff ++ "U))"
        , "    | (((" ++ show (mask32 sz) ++ "U & v) << " ++ show boff ++ "U));"
        , "}"
        ]

    mkWholeSet :: String -> Endianness -> String -> [String] -> [AlignedBitRange] -> String
    mkWholeSet tn omega nm partNs ranges =
      let sizes   = map (fromIntegral . bitSizeABR) ranges :: [Int]
          shifts  = shiftsFor omega sizes
          total   = sum sizes
          argTy   = if total <= 32 then "unsigned int" else "uint64_t"
          lines'  = zipWith
                      (\n off ->
                          "  " ++ n ++ "(b, (unsigned int)((v >> " ++ show off ++ "U) & "
                          ++ show (mask32 (sizeAtOff (fromIntegral off) ranges)) ++ "U));")
                      partNs
                      shifts
      in unlines
        ( [ "void d_set_" ++ nm ++ "(" ++ tn ++ " *b, " ++ argTy ++ " v)"
          , "{"
          ]
          ++ lines'
          ++ [ "}" , "" ]
        )

-- ===== helpers =====

-- Sum of sizes (in bits) for a field; your bitSizeABR returns an Integer-sized "Size".
totalBits :: [AlignedBitRange] -> Integer
totalBits = sum . map bitSizeABR

-- Given a bit offset into the concatenated value, return the size
-- (in bits) of the part that contains that offset.
sizeAtOff :: Integer -> [AlignedBitRange] -> Integer
sizeAtOff off ranges =
  let sizes   = map bitSizeABR ranges
      offsets = scanl' (+) 0 sizes   -- [0, s0, s0+s1, ...]
      idx     = length (takeWhile (< off) offsets)
  in  sizes !! idx

-- Given field endianness ω and the bit-sizes of each part (low→high order),
-- return the shift offsets to place each part inside the whole value.
shiftsFor :: Endianness -> [Int] -> [Int]
shiftsFor ω sizes =
  let leOffs = scanl (+) 0 sizes
      total  = sum sizes
      beShift le s = total - (le + s)
  in case ω of
       LE -> leOffs
       ME -> leOffs         -- treat machine as LE unless you add per-target logic
       BE -> zipWith beShift leOffs sizes

-- mask for up to 32-bit parts (single word lane)
mask32 :: Integer -> Integer
mask32 n
  | n <= 0    = 0
  | n >= 32   = 0xFFFFFFFF
  | otherwise = (1 `shiftL` fromIntegral n) - 1
