{-# LANGUAGE OverloadedStrings #-}
module Cedar.CodeGen.CodeGen
  ( emitHeader
  , emitImpl
  ) where

import Data.Char (toUpper)
import Data.List (intercalate, scanl')
import Data.Bits (shiftL)
import Cedar.CodeGen.Allocation (AlignedBitRange(..))
import Cedar.Layout.ToCodeGen (CGStruct(..), CGField(..))
import Cedar.Layout.Surface (Endianness(..))

-- ===== public files =====

emitHeader :: CGStruct -> String
emitHeader (CGStruct typeName wordCount fields) =
  unlines
    [ "// This file is generated by Cedar"
    , ""
    , "#ifndef " ++ guard typeName ++ "__"
    , "#define " ++ guard typeName ++ "__"
    , ""
    , "#include <stdint.h>"
    , ""
    , "struct " ++ typeName ++ " {"
    , "  unsigned int data[" ++ show wordCount ++ "U];"
    , "};"
    , "typedef struct " ++ typeName ++ " " ++ typeName ++ ";"
    , ""
    ]
    ++ unlines (concatMap protoForField fields)
    ++ "#endif\n"
  where
    guard nm = map (\c -> if c == ' ' then '_' else toUpper c) nm
    cRetType f = if totalBits (cgRanges f) <= 32 then "unsigned int" else "uint64_t"
    protoForField f =
      [ "static inline " ++ cRetType f ++ " d_get_" ++ cgName f ++ "(" ++ typeName ++ " *b);"
      , "static inline void d_set_" ++ cgName f ++ "(" ++ typeName ++ " *b, " ++ cRetType f ++ " v);"
      , ""
      ]

emitImpl :: CGStruct -> String
emitImpl (CGStruct typeName _ fields) =
  unlines $
    [ "// This file is generated by Cedar"
    , ""
    , "#include <stdint.h>"
    , "#include \"" ++ map toLower' typeName ++ ".h\""
    , ""
    ]
    ++ concatMap (emitFieldFns typeName) fields
  where
    toLower' c | 'A' <= c && c <= 'Z' = toEnum (fromEnum c + 32)
               | otherwise            = c

-- ===== per-field code =====

emitFieldFns :: String -> CGField -> [String]
emitFieldFns typeName (CGField fname brs ω) =
  let partNames = [ "d_get_" ++ fname ++ "_part" ++ show i | i <- [0..length brs - 1] ]
      setPartNames = [ "d_set_" ++ fname ++ "_part" ++ show i | i <- [0..length brs - 1] ]
      -- getters for each part
      partGets  = zipWith (mkPartGet typeName) partNames brs
      -- final get that assembles them
      getFun    = mkWholeGet fname partNames brs
      -- setters for each part
      partSets  = zipWith (mkPartSet typeName) setPartNames brs
      -- final set that slices value
      setFun    = mkWholeSet fname setPartNames brs
  in partGets ++ [getFun] ++ partSets ++ [setFun]
  where
    mkPartGet tn nm (AlignedBitRange sz boff woff) =
      unlines
        [ "static inline unsigned int " ++ nm ++ "(" ++ tn ++ " *b)"
        , "{"
        , "  return (b->data[" ++ show woff ++ "U] >> " ++ show boff ++ "U) & " ++ show (mask32 sz) ++ "U;"
        , "}"
        ]
    mkWholeGet nm partNs ranges =
      let shifts = scanl' (+) 0 [ bitSizeABR r | r <- ranges ]
          terms  = zipWith (\n s -> "( (uint64_t)" ++ n ++ "(b) << " ++ show s ++ "U )") partNs shifts
          retTy  = if totalBits ranges <= 32 then "unsigned int" else "uint64_t"
      in  unlines
        [ "static inline " ++ retTy ++ " d_get_" ++ nm ++ "(" ++ typeName ++ " *b)"
        , "{"
        , "  return " ++ intercalate " | " terms ++ ";"
        , "}"
        ]
    mkPartSet tn nm (AlignedBitRange sz boff woff) =
      unlines
        [ "static inline void " ++ nm ++ "(" ++ tn ++ " *b, unsigned int v)"
        , "{"
        , "  b->data[" ++ show woff ++ "U] ="
        , "      (b->data[" ++ show woff ++ "U] & ~(" ++ show (mask32 sz) ++ "U << " ++ show boff ++ "U))"
        , "    | (((" ++ show (mask32 sz) ++ "U & v) << " ++ show boff ++ "U));"
        , "}"
        ]
    mkWholeSet nm partNs ranges =
      let offsets = scanl' (+) 0 [ bitSizeABR r | r <- ranges ]
          lines'  = zipWith
                      (\n off -> "  " ++ n ++ "(b, (unsigned int)((v >> " ++ show off ++ "U) & " ++ show (mask32 (sizeAtOff off ranges)) ++ "U));")
                      partNs offsets
          argTy   = if totalBits ranges <= 32 then "unsigned int" else "uint64_t"
      in unlines
        ( [ "static inline void d_set_" ++ nm ++ "(" ++ typeName ++ " *b, " ++ argTy ++ " v)"
          , "{"
          ]
          ++ lines'
          ++ [ "}" , "" ]
        )

-- helpers

totalBits :: [AlignedBitRange] -> Integer
totalBits = sum . map bitSizeABR

-- Given a bit offset into the concatenated value, return the size
-- (in bits) of the part that contains that offset.
sizeAtOff :: Integer -> [AlignedBitRange] -> Integer
sizeAtOff off ranges =
  let sizes   = map bitSizeABR ranges
      offsets = scanl' (+) 0 sizes   -- [0, s0, s0+s1, ...]
      idx     = length (takeWhile (< off) offsets)
  in  sizes !! idx

-- mask for up to 32-bit parts (single word lane)
mask32 :: Integer -> Integer
mask32 n
  | n <= 0    = 0
  | n >= 32   = 0xFFFFFFFF
  | otherwise = (1 `shiftL` fromIntegral n) - 1
