#pragma once
#include <stdint.h>
#include <stddef.h>

/* Generated by Cedar codegen */
typedef struct {
    uint8_t _b[12];
} Student;

void* Student_get_name(const Student* s);
void Student_set_name(Student* s, const void* v);

uint8_t Student_get_age(const Student* s);
void Student_set_age(Student* s, uint8_t v);

uint8_t Student_get_maths(const Student* s);
void Student_set_maths(Student* s, uint8_t v);

uint16_t Student_get_physics(const Student* s);
void Student_set_physics(Student* s, uint16_t v);

