{-# LANGUAGE OverloadedStrings #-}
module Cedar.CodeGen.EmitC
  ( Prim(..), CType(..), Endian(..)
  , Range(..), CField(..), CBoundStruct(..)
  , emitHeader, emitImpl
  , bytesNeeded
  ) where

import Data.List (intercalate)
import Data.Char (toLower)

-- ====== Mock AST structure after /semantic phase ======

data Prim = I8 | I16 | I32 | I64 | F32 | F64 | Ptr
  deriving (Eq, Show)

data CType
  = CPrim Prim
  | CPointer CType
  | CStruct [(String, CType)]
  deriving (Eq, Show)

data Endian = LE | BE deriving (Eq, Show)

data Range = Range { offsetBits :: Int, sizeBits :: Int }
  deriving (Eq, Show)

data CField = CField
  { fName   :: String
  , fType   :: CType
  , fRange  :: Range
  , fEndian :: Maybe Endian
  }
  deriving (Eq, Show)

data CBoundStruct = CBoundStruct
  { sName     :: String
  , sSizeBits :: Int  -- total bits needed (rounded up to byte boundary)
  , sFields   :: [CField]
  }
  deriving (Eq, Show)


emitHeader :: CBoundStruct -> String
emitHeader s =
  unlines
    [ "#pragma once"
    , "#include <stdint.h>"
    , "#include <stddef.h>"
    , ""
    , "/* Generated by Cedar codegen */"
    , "typedef struct {"
    , "    uint8_t _b[" ++ show (bytesNeeded (sSizeBits s)) ++ "];"
    , "} " ++ sName s ++ ";"
    , ""
    ] ++ unlines (concatMap (protoPair (sName s)) (sFields s))

emitImpl :: CBoundStruct -> String
emitImpl s =
  let guard = map toLower (sName s) ++ "_cedar_h"
  in unlines
    [ "#include <string.h>"
    , "#include <inttypes.h>"
    , "#include \"" ++ map toLower (sName s) ++ "_cedar.h\""
    , ""
    , "/* Bit helpers (LE). For BE fields, byte-swap at the call sites. */"
    , loadBitsLE
    , storeBitsLE
    , ""
    ] ++ unlines (concatMap (implPair (sName s)) (sFields s))

-- ====== Helpers ======

bytesNeeded :: Int -> Int
bytesNeeded bits = (bits + 7) `div` 8

ctypeC :: CType -> String
ctypeC (CPrim I8)   = "uint8_t"
ctypeC (CPrim I16)  = "uint16_t"
ctypeC (CPrim I32)  = "uint32_t"
ctypeC (CPrim I64)  = "uint64_t"
ctypeC (CPrim F32)  = "float"
ctypeC (CPrim F64)  = "double"
ctypeC (CPrim Ptr)  = "void*"
ctypeC (CPointer _) = "void*"         -- we normalize to void* at the boundary
ctypeC (CStruct _)  = "/*struct*/ void*" -- treat as opaque for now

-- field api names
getName :: String -> String -> String
getName sN fN = sN ++ "_get_" ++ fN

setName :: String -> String -> String
setName sN fN = sN ++ "_set_" ++ fN

-- generate prototypes (header)
protoPair :: String -> CField -> [String]
protoPair sN f =
  let nm   = fName f
      r    = fRange f
      cty  = ctypeC (fType f)
      getter = case fType f of
        CPrim Ptr   -> "void*"
        CPointer _  -> "void*"
        _           -> cty
      setter = case fType f of
        CPrim Ptr   -> "const void*"
        CPointer _  -> "const void*"
        _           -> cty
   in [ getter ++ " " ++ getName sN nm ++ "(const " ++ sN ++ "* s);"
      , "void " ++ setName sN nm ++ "(" ++ sN ++ "* s, " ++ setter ++ " v);"
      , ""
      ]

-- generate implementations (c file)
implPair :: String -> CField -> [String]
implPair sN f =
  let nm     = fName f
      Range off len = fRange f
      load  = "load_bits_le(s->_b, "  ++ show off ++ ", " ++ show len ++ ")"
      store v= "store_bits_le(s->_b, " ++ show off ++ ", " ++ show len ++ ", " ++ v ++ ")"
      -- endian shim for BE word fields (we only swap 16/32/64)
      maybeSwapIn  v = case fEndian f of
        Just BE -> case fType f of
          CPrim I16 -> "(uint16_t)__builtin_bswap16(" ++ v ++ ")"
          CPrim I32 -> "(uint32_t)__builtin_bswap32(" ++ v ++ ")"
          CPrim I64 -> "(uint64_t)__builtin_bswap64(" ++ v ++ ")"
          _         -> v
        _ -> v
      maybeSwapOut v = case fEndian f of
        Just BE -> case fType f of
          CPrim I16 -> "(uint16_t)__builtin_bswap16(" ++ v ++ ")"
          CPrim I32 -> "(uint32_t)__builtin_bswap32(" ++ v ++ ")"
          CPrim I64 -> "(uint64_t)__builtin_bswap64(" ++ v ++ ")"
          _         -> v
        _ -> v
      -- getter line
      getterRet = case fType f of
        CPrim Ptr   -> "void*"
        CPointer _  -> "void*"
        _           -> ctypeC (fType f)
      getterBody = case fType f of
        CPrim Ptr   -> "    uint64_t u = " ++ load ++ ";\n    return (void*)(uintptr_t)u;"
        CPointer _  -> "    uint64_t u = " ++ load ++ ";\n    return (void*)(uintptr_t)u;"
        CPrim I8    -> "    return (uint8_t)"  ++ load ++ ";"
        CPrim I16   -> "    return (uint16_t)" ++ maybeSwapOut ("(uint16_t)" ++ load) ++ ";"
        CPrim I32   -> "    return (uint32_t)" ++ maybeSwapOut ("(uint32_t)" ++ load) ++ ";"
        CPrim I64   -> "    return (uint64_t)" ++ maybeSwapOut ("(uint64_t)" ++ load) ++ ";"
        CPrim F32   -> unlines
            [ "    uint32_t u = (uint32_t)" ++ load ++ ";"
            , "    float f;"
            , "    memcpy(&f, &u, sizeof(float));"
            , "    return f;"
            ]
        CPrim F64   -> unlines
            [ "    uint64_t u = (uint64_t)" ++ load ++ ";"
            , "    double d;"
            , "    memcpy(&d, &u, sizeof(double));"
            , "    return d;"
            ]
        CStruct _   -> "    return (void*)(uintptr_t)" ++ load ++ "; /* opaque */"
      -- setter line
      setterArgTy = case fType f of
        CPrim Ptr   -> "const void*"
        CPointer _  -> "const void*"
        _           -> ctypeC (fType f)
      setterBody = case fType f of
        CPrim Ptr   -> "    uintptr_t u = (uintptr_t)v;\n    " ++ store "(uint64_t)u" ++ ";"
        CPointer _  -> "    uintptr_t u = (uintptr_t)v;\n    " ++ store "(uint64_t)u" ++ ";"
        CPrim I8    -> "    " ++ store "(uint64_t)v" ++ ";"
        CPrim I16   -> "    " ++ store ("(uint64_t)" ++ maybeSwapIn "v") ++ ";"
        CPrim I32   -> "    " ++ store ("(uint64_t)" ++ maybeSwapIn "v") ++ ";"
        CPrim I64   -> "    " ++ store ("(uint64_t)" ++ maybeSwapIn "v") ++ ";"
        CPrim F32   -> unlines
            [ "    uint32_t u;"
            , "    memcpy(&u, &v, sizeof(uint32_t));"
            , "    " ++ store "(uint64_t)u" ++ ";"
            ]
        CPrim F64   -> unlines
            [ "    uint64_t u;"
            , "    memcpy(&u, &v, sizeof(uint64_t));"
            , "    " ++ store "u" ++ ";"
            ]
        CStruct _   -> "    /* opaque store not supported */"
  in
    [ getterRet ++ " " ++ getName sN nm ++ "(const " ++ sN ++ "* s)"
    , "{"
    , getterBody
    , "}"
    , ""
    , "void " ++ setName sN nm ++ "(" ++ sN ++ "* s, " ++ setterArgTy ++ " v)"
    , "{"
    , setterBody
    , "}"
    , ""
    ]

-- ====== C snippets ======

loadBitsLE :: String
loadBitsLE = unlines
  [ "static inline uint64_t load_bits_le(const uint8_t* b, size_t bitOff, size_t bitLen) {"
  , "    size_t byteOff = bitOff >> 3;"
  , "    size_t endBit  = bitOff + bitLen;"
  , "    size_t endByte = (endBit + 7) >> 3;"
  , "    uint64_t acc = 0;"
  , "    for (size_t i = 0; i < endByte - byteOff && i < 8; ++i) {"
  , "        acc |= ((uint64_t)b[byteOff + i]) << (8*i);"
  , "    }"
  , "    acc >>= (bitOff & 7);"
  , "    if (bitLen >= 64) return acc;"
  , "    return acc & ((1ULL << bitLen) - 1ULL);"
  , "}"
  ]

storeBitsLE :: String
storeBitsLE = unlines
  [ "static inline void store_bits_le(uint8_t* b, size_t bitOff, size_t bitLen, uint64_t value) {"
  , "    size_t byteOff = bitOff >> 3;"
  , "    size_t endBit  = bitOff + bitLen;"
  , "    size_t endByte = (endBit + 7) >> 3;"
  , "    uint64_t v = value << (bitOff & 7);"
  , "    for (size_t i = 0; i < endByte - byteOff && i < 8; ++i) {"
  , "        uint8_t cur = b[byteOff + i];"
  , "        uint8_t newb = (uint8_t)(v >> (8*i));"
  , "        uint8_t mask = 0xFF;"
  , "        size_t bitStart = (byteOff + i) * 8;"
  , "        size_t bitEnd   = bitStart + 8;"
  , "        size_t coverS   = (bitOff > bitStart) ? (bitOff - bitStart) : 0;"
  , "        size_t coverE   = (endBit < bitEnd) ? (bitEnd - endBit) : 0;"
  , "        if (bitLen < 64) {"
  , "            uint8_t left  = (coverS >= 8) ? 0 : (uint8_t)(0xFF << coverS);"
  , "            uint8_t right = (coverE >= 8) ? 0 : (uint8_t)(0xFF >> coverE);"
  , "            mask = (uint8_t)(left & right);"
  , "        }"
  , "        cur &= ~mask;"
  , "        cur |= (newb & mask);"
  , "        b[byteOff + i] = cur;"
  , "    }"
  , "}"
  ]
